// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp9_6JGV5I9TKDXBRyL9tVzWf6t0WNoo8',
    appId: '1:522053783800:web:106cd2ec66305b11406b0d',
    messagingSenderId: '522053783800',
    projectId: 'dontblink-3d0f6',
    authDomain: 'dontblink-3d0f6.firebaseapp.com',
    storageBucket: 'dontblink-3d0f6.firebasestorage.app',
    measurementId: 'G-YTEKD65G1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-AXVBxb0Y7QMVHsGFqDGVOfU2Yq-kMXU',
    appId: '1:522053783800:android:dac012a39c0b42aa406b0d',
    messagingSenderId: '522053783800',
    projectId: 'dontblink-3d0f6',
    storageBucket: 'dontblink-3d0f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtDRsx6UEhLtxkrAPRmbvmbkO5jpfFZfk',
    appId: '1:522053783800:ios:0c1a4eebdb1e3078406b0d',
    messagingSenderId: '522053783800',
    projectId: 'dontblink-3d0f6',
    storageBucket: 'dontblink-3d0f6.firebasestorage.app',
    iosBundleId: 'com.example.dontBlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtDRsx6UEhLtxkrAPRmbvmbkO5jpfFZfk',
    appId: '1:522053783800:ios:0c1a4eebdb1e3078406b0d',
    messagingSenderId: '522053783800',
    projectId: 'dontblink-3d0f6',
    storageBucket: 'dontblink-3d0f6.firebasestorage.app',
    iosBundleId: 'com.example.dontBlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp9_6JGV5I9TKDXBRyL9tVzWf6t0WNoo8',
    appId: '1:522053783800:web:dba48b6b62e95df6406b0d',
    messagingSenderId: '522053783800',
    projectId: 'dontblink-3d0f6',
    authDomain: 'dontblink-3d0f6.firebaseapp.com',
    storageBucket: 'dontblink-3d0f6.firebasestorage.app',
    measurementId: 'G-BV2GF9T9LL',
  );
}
